upload sarif file

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -27,13 +27,13 @@ jobs:
     steps:
     - uses: actions/checkout@v3
 
-    - name: Dump github context
-      run:   echo "$GITHUB_CONTEXT"
-      shell: bash
-      env:
-        GITHUB_CONTEXT: ${{ toJson(github) }}
-    - name: Test variables
-      run: echo "hello from $REPO"
+    # - name: Dump github context
+    #   run:   echo "$GITHUB_CONTEXT"
+    #   shell: bash
+    #   env:
+    #     GITHUB_CONTEXT: ${{ toJson(github) }}
+    # - name: Test variables
+    #   run: echo "hello from $REPO"
     - name: Run Bridgecrew 
       id: Bridgecrew
       uses: bridgecrewio/bridgecrew-action@master
@@ -46,11 +46,23 @@ jobs:
         #skip_check: CKV_AWS_1 # optional: skip a specific check_id. can be comma separated list
         soft_fail: true
         #framework: terraform # optional: run only on a specific infrastructure {cloudformation,terraform,kubernetes,all}
-        output_format: cli
+        output_format: cli,sarif
+        output_file_path: console,results.sarif
         quiet: false
         external_checks_dirs: ./checkov
         download_external_modules: true # optional: download external terraform modules from public git repositories and terraform registry
         #log_level: DEBUG # optional: set log level. Default WARNING
+    - name: Upload SARIF file
+      uses: github/codeql-action/upload-sarif@v2
+        
+        # Results are generated only on a success or failure
+        # this is required since GitHub by default won't run the next step
+        # when the previous one has failed. Security checks that do not pass will 'fail'.
+        # An alternative is to add `continue-on-error: true` to the previous step
+        # Or 'soft_fail: true' to checkov.
+      if: success() || failure()
+      with:
+        sarif_file: results.sarif
     - name: Assign build number
       run: |
         echo "BUILD_ID=$(date +'%y_%m_%d')" >> $GITHUB_ENV
